table-order/table-order

app/menu/[id]/page.tsx
package.json

refactor: MenuDetailPage 아이콘 라이브러리 변경 및 package.json 정리

---

app/components/MainHeader.tsx
app/layout.tsx
app/page.tsx

화면 상단 
뒤로가기, 주문내역 포함된 헤더 추가
root page.tsx에 padding 추가

feat: Header 컴포넌트 추가 및 root page 더미 데이터 추가

---

app/components/CustomButton.tsx
app/components/MenuDetailContent.tsx
app/components/MenuItem.tsx
app/menu/[id]/page.tsx
app/store/store.ts
package.json
pnpm-lock.yaml

store.ts 추가
- 아이템 추가
- 카트에서 삭제
- 수량 업데이트
- persist 미들웨어

zustand로 cart store 추가

---

app/cart/page.tsx

updateQuantity, deleteItem 추가 (store로 수정할 예정)

feat: updateQuantity, deleteItem 추가

---

app/components/MainHeader.tsx
app/components/MenuItem.tsx
app/components/MenuList.tsx
app/components/NavBar.tsx
app/components/NavItem.tsx
app/hooks/useHash.ts
app/page.tsx
package.json
pnpm-lock.yaml

- 커스텀훅용 hooks 디렉토리 추가
- react-intersection-observer 라이브러리 추가

카테고리 tab 추가 및 ui 변경

---

app/components/MenuList.tsx
app/components/NavBar.tsx
app/components/NavItem.tsx
app/menu/[id]/page.tsx
app/page.tsx
next.config.ts
package.json
pnpm-lock.yaml
utils/supabase/client.ts
utils/supabase/server.ts

- UI 임시로 하드코딩, 추후 변수로 변환 예정입니다.
- MenuList 타입이나 카테고리별로 필터링 기능 다시 체크

feat: supabase 추가 및 UI 수정

---

app/components/CustomButton.tsx
app/components/MainHeader.tsx
app/components/MenuList.tsx
app/components/NavBar.tsx
app/globals.css
app/order/history/page.tsx
app/store/store.ts

- store에 order 상태와 주문 완료 함수 추가

feat: 주문내역 페이지 추가 그외

---

app/components/NavBar.tsx
app/components/NavItem.tsx
app/globals.css
app/order/history/page.tsx
next.config.ts

- 애니메이션 추가
- 직원호출 버튼 따로 만들어야 함
- 카테고리 모달창이 열릴때 현재 active 인 카테고리가 반영 안됨

feat: 카테고리 더보기 버튼 추가

---

app/components/FixedBottomCTA.tsx
app/components/FooterInfo.tsx
app/components/MainFooter.tsx
app/components/MenuList.tsx
app/components/NavBar.tsx
app/page.tsx

- 나중에 원산지 등 가게정보 db에서 가져와야함
- 모달 버튼에 가려져서 z값 변경함

feat: MainFooter 추가

---

app/cart/page.tsx
app/components/MenuDetailContent.tsx
app/components/Toast.tsx
app/components/ToastPortal.tsx
app/layout.tsx
app/store/toastStore.ts
package.json
pnpm-lock.yaml

**작업사항**
1. 전역상태 toastStore 추가
2. Toast UI 컴포넌트 추가
3. ToastPortal 클라이언트 컴포넌트 추가
4. MenuDetail 페이지에서 장바구니 담기 클릭시 "장바구니에 메뉴를 추가했어요"
5. cart페이지에서 삭제시 "메뉴를 삭제했어요"
(추후 toast 애니메이션 추가예정)

feat: Feature/toast store

---

app/components/MenuItem.tsx
app/order/complete/page.tsx

feat: 주문 완료 라우팅만 추가 및 이미지 에러 수정

---

app/cart/page.tsx
app/components/NavBar.tsx

**작업사항**
build 에러 수정
-totalPrice제거
-index제거

fix: build 시 에러 수정

---

app/components/CallButton.tsx
app/components/MainFooter.tsx
app/components/MainHeader.tsx
app/components/MenuList.tsx
app/components/NavBar.tsx
app/components/NavItem.tsx
app/page.tsx
app/store/navStore.ts

CallButton 컴포넌트 추가 외 NavItem 등 스타일 변경

feat: 직원호출 버튼 추가

---

app/components/MenuItem.tsx
app/components/MenuList.tsx

feat: MenuItem에 대한 터치 애니메이션 추가

---

app/components/CustomBadge.tsx
app/components/MenuItem.tsx
app/components/MenuList.tsx

- db MenuItem Table에 tag column 추가

feat: CustomBadge 컴포넌트 추가

---

app/api/confirm/payment/route.ts
app/api/confirm/widget/route.ts
app/cart/page.tsx
app/components/Fail.tsx
app/components/MenuDetailContent.tsx
app/components/MenuItem.tsx
app/components/NavBar.tsx
app/fail/page.tsx
app/globals.css
app/order/checkout/page.tsx
app/store/store.ts
package.json
pnpm-lock.yaml

- @tosspayments/tosspayments-sdk 추가
- globals.css에 일부 css 추가
- Cart에서 주문하기 버튼 클릭시 결제 페이지로 이동
- completeOrder에서 새 주문 삽입 위치 맨 앞으로 변경

feat: TossPayments SDK 추가  및 결제 관련 컴포넌트 추가

---

app/components/CustomButton.tsx
app/components/SetupUserChannel.tsx
app/components/UserCount.tsx
app/layout.tsx
app/page.tsx
app/store/channelStore.ts
app/store/userStore.ts

**작업사항**
1. 실시간 접속자 수 화면에 보여줄 UI 컴포넌트 UserCount 추가
2. 전역 채널 관리용 channelStore 추가
3. 전역 접속자 관리용 userStore 추가
4. 채널생성과 구독설정하는 SetupUserChannel 컴포넌트 추가

feat: Add user channel

---

app/cart/page.tsx
app/components/FixedBottomCTA.tsx
app/components/MenuDetailContent.tsx
app/order/checkout/page.tsx
next.config.ts
utils/storage.ts

- CartPage 컴포넌트에서 장바구니 항목을 가져오고 업데이트하는 기능
- FixedBottomCTA를 업데이트하여 실시간 장바구니 변경 사항 반영
- 사용자와 멤버의 장바구니 항목을 분리
- MenuDetailContent에서 Supabase를 통해 장바구니에 항목 추가 기능 구현

feat: 장바구니 데이터 관리를 위해 Supabase 클라이언트 추가.

---

app/components/SetupUserChannel.tsx

SetupUserChannel 컴포넌트의 userId 로직 수정

refactor: userId 로직 수정

---

app/cart/page.tsx

**cart page에서 같은메뉴 삭제시 동시삭제되는 오류해결**
- handleDelete함수에 itemId > id로 변경
- itemId가 아닌 cart테이블의 id 기준으로 delete 수행

fix: 같은메뉴 삭제시 동시삭제되는 오류해결

---

app/cart/page.tsx

cart 수량 변경시
- 1 이하일시 disabled
- 멤버 메뉴 수량 변경 가능
- 수량 변경시 재정렬 되던 현상 수정

refactor: 카트 수량 변경 수정 및 순서 오류 수정

---

app/cart/page.tsx
app/components/FixedBottomCTA.tsx
app/components/MenuDetailContent.tsx

- Cart 내에서 수량 변경 버튼 클릭시에는 토스트 표시 안됨

feat: 카트 업데이트 실시간 반영 및 수량 변경 시 토스트 메시지 추가

---

app/components/OrderHistory.tsx
app/components/SetupCartChannel.tsx
app/components/UserCount.tsx
app/order/complete/page.tsx
app/order/history/page.tsx

주문 내역을 Supabase에서 가져오는 로직 추가
주문 아이템 구조 변경 및 관련 상태 관리 개선
주문 내역이 없을 경우의 UI 처리 개선
SetupCartChannel에서 주문 완료 시 토스트 메시지 추가
CompletePage에서 카트 내용을 주문으로 이동하는 로직 구현
HistoryPage에서 UI 개선 및 이미지 추가

refactor: OrderHistory 컴포넌트 리팩토링 및 Supabase 연동

---

app/components/FixedBottomCTA.tsx
app/components/SetupCartChannel.tsx
app/components/SetupUserChannel.tsx

- 토스트 중복 표시 방지
- console.log 삭제 및 주석처리

refactor: FixedBottomCTA에서 addToast 로직 주석처리

---

app/components/CallButton.tsx
app/components/NavBar.tsx

웹 접근성 개선
1. NavBar의 카테고리 선택버튼에 aria-label 추가
2. 직원호출 버튼 image에 중복된 alt 속성값 제거

fix: 버튼 접근성 개선
